name: peliculas_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_card_swiper: ^6.0.0
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_card_swipper: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
